/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootLayoutRouteImport } from './routes/_rootLayout/route'
import { Route as IndexImport } from './routes/index'
import { Route as RootLayoutTransactionsIndexImport } from './routes/_rootLayout/transactions/index'
import { Route as RootLayoutSettingsIndexImport } from './routes/_rootLayout/settings/index'
import { Route as RootLayoutReportsIndexImport } from './routes/_rootLayout/reports/index'
import { Route as RootLayoutImportIndexImport } from './routes/_rootLayout/import/index'
import { Route as RootLayoutDashboardIndexImport } from './routes/_rootLayout/dashboard/index'
import { Route as RootLayoutBudgetsIndexImport } from './routes/_rootLayout/budgets/index'
import { Route as RootLayoutAccountsIndexImport } from './routes/_rootLayout/accounts/index'

// Create/Update Routes

const RootLayoutRouteRoute = RootLayoutRouteImport.update({
  id: '/_rootLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RootLayoutTransactionsIndexRoute =
  RootLayoutTransactionsIndexImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => RootLayoutRouteRoute,
  } as any)

const RootLayoutSettingsIndexRoute = RootLayoutSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)

const RootLayoutReportsIndexRoute = RootLayoutReportsIndexImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)

const RootLayoutImportIndexRoute = RootLayoutImportIndexImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)

const RootLayoutDashboardIndexRoute = RootLayoutDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)

const RootLayoutBudgetsIndexRoute = RootLayoutBudgetsIndexImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)

const RootLayoutAccountsIndexRoute = RootLayoutAccountsIndexImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => RootLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_rootLayout': {
      id: '/_rootLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_rootLayout/accounts/': {
      id: '/_rootLayout/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof RootLayoutAccountsIndexImport
      parentRoute: typeof RootLayoutRouteImport
    }
    '/_rootLayout/budgets/': {
      id: '/_rootLayout/budgets/'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof RootLayoutBudgetsIndexImport
      parentRoute: typeof RootLayoutRouteImport
    }
    '/_rootLayout/dashboard/': {
      id: '/_rootLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof RootLayoutDashboardIndexImport
      parentRoute: typeof RootLayoutRouteImport
    }
    '/_rootLayout/import/': {
      id: '/_rootLayout/import/'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof RootLayoutImportIndexImport
      parentRoute: typeof RootLayoutRouteImport
    }
    '/_rootLayout/reports/': {
      id: '/_rootLayout/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof RootLayoutReportsIndexImport
      parentRoute: typeof RootLayoutRouteImport
    }
    '/_rootLayout/settings/': {
      id: '/_rootLayout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof RootLayoutSettingsIndexImport
      parentRoute: typeof RootLayoutRouteImport
    }
    '/_rootLayout/transactions/': {
      id: '/_rootLayout/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof RootLayoutTransactionsIndexImport
      parentRoute: typeof RootLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface RootLayoutRouteRouteChildren {
  RootLayoutAccountsIndexRoute: typeof RootLayoutAccountsIndexRoute
  RootLayoutBudgetsIndexRoute: typeof RootLayoutBudgetsIndexRoute
  RootLayoutDashboardIndexRoute: typeof RootLayoutDashboardIndexRoute
  RootLayoutImportIndexRoute: typeof RootLayoutImportIndexRoute
  RootLayoutReportsIndexRoute: typeof RootLayoutReportsIndexRoute
  RootLayoutSettingsIndexRoute: typeof RootLayoutSettingsIndexRoute
  RootLayoutTransactionsIndexRoute: typeof RootLayoutTransactionsIndexRoute
}

const RootLayoutRouteRouteChildren: RootLayoutRouteRouteChildren = {
  RootLayoutAccountsIndexRoute: RootLayoutAccountsIndexRoute,
  RootLayoutBudgetsIndexRoute: RootLayoutBudgetsIndexRoute,
  RootLayoutDashboardIndexRoute: RootLayoutDashboardIndexRoute,
  RootLayoutImportIndexRoute: RootLayoutImportIndexRoute,
  RootLayoutReportsIndexRoute: RootLayoutReportsIndexRoute,
  RootLayoutSettingsIndexRoute: RootLayoutSettingsIndexRoute,
  RootLayoutTransactionsIndexRoute: RootLayoutTransactionsIndexRoute,
}

const RootLayoutRouteRouteWithChildren = RootLayoutRouteRoute._addFileChildren(
  RootLayoutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof RootLayoutRouteRouteWithChildren
  '/accounts': typeof RootLayoutAccountsIndexRoute
  '/budgets': typeof RootLayoutBudgetsIndexRoute
  '/dashboard': typeof RootLayoutDashboardIndexRoute
  '/import': typeof RootLayoutImportIndexRoute
  '/reports': typeof RootLayoutReportsIndexRoute
  '/settings': typeof RootLayoutSettingsIndexRoute
  '/transactions': typeof RootLayoutTransactionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof RootLayoutRouteRouteWithChildren
  '/accounts': typeof RootLayoutAccountsIndexRoute
  '/budgets': typeof RootLayoutBudgetsIndexRoute
  '/dashboard': typeof RootLayoutDashboardIndexRoute
  '/import': typeof RootLayoutImportIndexRoute
  '/reports': typeof RootLayoutReportsIndexRoute
  '/settings': typeof RootLayoutSettingsIndexRoute
  '/transactions': typeof RootLayoutTransactionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_rootLayout': typeof RootLayoutRouteRouteWithChildren
  '/_rootLayout/accounts/': typeof RootLayoutAccountsIndexRoute
  '/_rootLayout/budgets/': typeof RootLayoutBudgetsIndexRoute
  '/_rootLayout/dashboard/': typeof RootLayoutDashboardIndexRoute
  '/_rootLayout/import/': typeof RootLayoutImportIndexRoute
  '/_rootLayout/reports/': typeof RootLayoutReportsIndexRoute
  '/_rootLayout/settings/': typeof RootLayoutSettingsIndexRoute
  '/_rootLayout/transactions/': typeof RootLayoutTransactionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/accounts'
    | '/budgets'
    | '/dashboard'
    | '/import'
    | '/reports'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/accounts'
    | '/budgets'
    | '/dashboard'
    | '/import'
    | '/reports'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_rootLayout'
    | '/_rootLayout/accounts/'
    | '/_rootLayout/budgets/'
    | '/_rootLayout/dashboard/'
    | '/_rootLayout/import/'
    | '/_rootLayout/reports/'
    | '/_rootLayout/settings/'
    | '/_rootLayout/transactions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RootLayoutRouteRoute: typeof RootLayoutRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RootLayoutRouteRoute: RootLayoutRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_rootLayout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_rootLayout": {
      "filePath": "_rootLayout/route.tsx",
      "children": [
        "/_rootLayout/accounts/",
        "/_rootLayout/budgets/",
        "/_rootLayout/dashboard/",
        "/_rootLayout/import/",
        "/_rootLayout/reports/",
        "/_rootLayout/settings/",
        "/_rootLayout/transactions/"
      ]
    },
    "/_rootLayout/accounts/": {
      "filePath": "_rootLayout/accounts/index.tsx",
      "parent": "/_rootLayout"
    },
    "/_rootLayout/budgets/": {
      "filePath": "_rootLayout/budgets/index.tsx",
      "parent": "/_rootLayout"
    },
    "/_rootLayout/dashboard/": {
      "filePath": "_rootLayout/dashboard/index.tsx",
      "parent": "/_rootLayout"
    },
    "/_rootLayout/import/": {
      "filePath": "_rootLayout/import/index.tsx",
      "parent": "/_rootLayout"
    },
    "/_rootLayout/reports/": {
      "filePath": "_rootLayout/reports/index.tsx",
      "parent": "/_rootLayout"
    },
    "/_rootLayout/settings/": {
      "filePath": "_rootLayout/settings/index.tsx",
      "parent": "/_rootLayout"
    },
    "/_rootLayout/transactions/": {
      "filePath": "_rootLayout/transactions/index.tsx",
      "parent": "/_rootLayout"
    }
  }
}
ROUTE_MANIFEST_END */
